services:

  # Pull desde base de datos
  postgres:
    image: postgres:16-alpine
    container_name: spool-postgres
    environment:
      POSTGRES_USER: spool_user
      POSTGRES_PASSWORD: spool_pass
      POSTGRES_DB: spool_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U spool_user -d spool_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: [ pull-db ]

  # Pull desde API REST
  mock-rest-api:
    image: wiremock/wiremock:latest
    container_name: spool-mock-api
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    profiles: [pull-api]

  # Stream desde Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: spool-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    depends_on: [zookeeper]
    profiles: [stream]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: spool-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    profiles: [stream]

volumes:
  postgres_data:
